#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash".

# Get the PID and process name of processes containing the word "bash"
# shellcheck disable=SC2009
pgrep -l bash
