#!/usr/bin/env bash
# This script stops the "4-to_infinity_and_beyond" process without using kill or killall.

# Use pkill to stop the "4-to_infinity_and_beyond" process
pkill -f "4-to_infinity_and_beyond"

echo "Process stopped"
